package org.uiflow.desktop.chart;

import org.uiflow.desktop.chart.axis.*;
import org.uiflow.desktop.chart.chartlayer.BarLayer;
import org.uiflow.desktop.chart.chartlayer.LineLayer;
import org.uiflow.desktop.chart.dataseries.ArrayListDataSeries;
import org.uiflow.desktop.chart.dataseries.DataSeries;
import org.uiflow.desktop.chart.dataseries.RelativePosMapper;
import org.uiflow.desktop.gradient.ColorGradients;
import org.uiflow.desktop.ui.SimpleFrame;
import org.uiflow.desktop.utils.ColorMapper;

import java.util.Date;

/**
 *
 */
public class ChartExample {

    public static void main(String[] args) {

        DefaultChart chart = new DefaultChart("Global Warming vs Number Of Pirates");

        final long startTime = Date.UTC(-200, 1, 1, 0, 0, 0);
        final long endTime = Date.UTC(100, 1, 1, 0, 0, 0);
        final long oneYear = (long) (365.25*24*60*60*1000);


        final TimeAxis timeAxis = new TimeAxis();
        final Axis<Integer> pirateCountAxis = new Axis<Integer>("Number of Pirates", Integer.class);
        final Axis<Double> globalWarmingAxis = new Axis<Double>("Global Warming", Double.class);

        final AxisView<Long> timeAxisView = chart.addAxis(timeAxis, AxisOrientation.HORIZONTAL_BOTTOM, startTime, endTime);
        final AxisView<Integer> numberOfPiratesAxisView = chart.addAxis(pirateCountAxis,
                                                                        AxisOrientation.VERTICAL_RIGHT,
                                                                        0, 750);
        final AxisView<Double> globalWarmingAxisView = chart.addAxis(globalWarmingAxis,
                                                                     AxisOrientation.VERTICAL_LEFT,
                                                                     -1.0, 1.0);


        // This data is professionally generated by carefully pulling numbers out of thin air, and should not be trusted.
        // TODO: We need some gradient backed data series, that allows placing values with arbitrary indexes.  May need to generify gradient first though.
        DataSeries<Long, Integer> numberOfPiratesOverTime = new ArrayListDataSeries<Long, Integer>(timeAxis, startTime, 11*oneYear,
                                                                                                   30,
                                                                                                   65,
                                                                                                   123,
                                                                                                   150,
                                                                                                   220,
                                                                                                   303,
                                                                                                   554,
                                                                                                   434,
                                                                                                   421,
                                                                                                   443,
                                                                                                   389,
                                                                                                   323,
                                                                                                   298,
                                                                                                   212,
                                                                                                   187,
                                                                                                   123,
                                                                                                   87,
                                                                                                   65,
                                                                                                   43,
                                                                                                   55,
                                                                                                   32,
                                                                                                   17,
                                                                                                   6,
                                                                                                   4,
                                                                                                   3,
                                                                                                   0,
                                                                                                   2,
                                                                                                   0,
                                                                                                   0,
                                                                                                   1,
                                                                                                   0,
                                                                                                   0);

        DataSeries<Long, Double> globalWarmingOverTime = new ArrayListDataSeries<Long, Double>(timeAxis, startTime, 11*oneYear,
                                                                                                   0.0,
                                                                                                   -0.1,
                                                                                                   -0.12,
                                                                                                   -0.3,
                                                                                                   -0.1,
                                                                                                   0.1,
                                                                                                   0.05,
                                                                                                   0.1,
                                                                                                   0.2,
                                                                                                   0.23,
                                                                                                   0.12,
                                                                                                   0.32,
                                                                                                   0.43,
                                                                                                   0.54,
                                                                                                   0.23,
                                                                                                   0.13,
                                                                                                   0.32,
                                                                                                   0.45,
                                                                                                   0.23,
                                                                                                   0.65,
                                                                                                   0.23,
                                                                                                   0.12,
                                                                                                   0.23,
                                                                                                   0.56,
                                                                                                   0.87,
                                                                                                   0.43);

        // TODO: Easier way to specify that a channel should use a RelativePosMapper.  Maybe a method for it.

        final BarLayer<Long, Integer> pirateCountLayer = chart.addLayer(new BarLayer<Long, Integer>(timeAxis, pirateCountAxis));
        pirateCountLayer.barHeight.setData(numberOfPiratesOverTime);
        pirateCountLayer.barColor.setData(numberOfPiratesOverTime,
                                     new RelativePosMapper<Integer>(numberOfPiratesAxisView),
                                     new ColorMapper<Double>(ColorGradients.RAINBOW));

        final LineLayer<Long, Double> globalWarmingLayer = chart.addLayer(new LineLayer<Long, Double>(timeAxis, globalWarmingAxis));
        globalWarmingLayer.lineHeight.setData(globalWarmingOverTime);
        globalWarmingLayer.lineColor.setData(globalWarmingOverTime,
                                             new RelativePosMapper<Double>(globalWarmingAxisView),
                                             new ColorMapper<Double>(ColorGradients.GREYSCALE));
        globalWarmingLayer.setDefaultLineThickness(5);

        new SimpleFrame("Chart Example", chart.getUi());

    }

}
